<template>
  <div class="loadingio-spinner-spin-x56emwocbqb"  :style="{'width': `${124 * scale}px`, 'height': `${124 * scale}px`}">
    <div class="ldio-ljewonjwdn9" :style="{'transform':`translateZ(0) scale(${scale})`}">
      <div>
        <div></div>
      </div>
      <div>
        <div></div>
      </div>
      <div>
        <div></div>
      </div>
      <div>
        <div></div>
      </div>
      <div>
        <div></div>
      </div>
      <div>
        <div></div>
      </div>
      <div>
        <div></div>
      </div>
      <div>
        <div></div>
      </div>
    </div>
  </div>
  <div class="text-center loading-text">Loading</div>
</template>
<script>
export default {
  name: 'LoadingSpinner',
  props: {
    scale: {
      type: Number,
      default: 1
    }
  }
}
</script>
<style>
/* area loading */
.area-loading {
  position: relative;
  display: flex;
  align-items: center;
  background-color: var(--bs-body-bg);
  justify-content: center;
  flex-wrap: nowrap;
}
.area-loading .area-loading-wrap {
  position: absolute;
  z-index: 500;
}

.vl-overlay .vl-background {
  background-color: var(--bs-body-bg);
  opacity: 1;
}
.loadingio-spinner-spin-x56emwocbqb {
  width:124px;
  height:124px;
}
.loading-text {
  color: var(--bs-primary);
}
@keyframes ldio-ljewonjwdn9 {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.5,1.5);
  } 100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1,1);
  }
}
.ldio-ljewonjwdn9 div > div {
  position: absolute;
  width: 12.4px;
  height: 12.4px;
  border-radius: 50%;
  background:  var(--bs-primary);
  animation: ldio-ljewonjwdn9 1s linear infinite;
}.ldio-ljewonjwdn9 div:nth-child(1) > div {
  left: 93px;
  top: 56px;
  animation-delay: -0.875s;
}
.ldio-ljewonjwdn9 > div:nth-child(1) {
  transform: rotate(0deg);
  transform-origin: 99.2px 62.2px;
}.ldio-ljewonjwdn9 div:nth-child(2) > div {
  left: 82px;
  top: 82px;
  animation-delay: -0.75s;
}
.ldio-ljewonjwdn9 > div:nth-child(2) {
  transform: rotate(45deg);
  transform-origin: 88.2px 88.2px;
}.ldio-ljewonjwdn9 div:nth-child(3) > div {
  left: 56px;
  top: 93px;
  animation-delay: -0.625s;
}
.ldio-ljewonjwdn9 > div:nth-child(3) {
  transform: rotate(90deg);
  transform-origin: 62.2px 99.2px;
}.ldio-ljewonjwdn9 div:nth-child(4) > div {
  left: 29px;
  top: 82px;
  animation-delay: -0.5s;
}
.ldio-ljewonjwdn9 > div:nth-child(4) {
  transform: rotate(135deg);
  transform-origin: 35.2px 88.2px;
}.ldio-ljewonjwdn9 div:nth-child(5) > div {
  left: 19px;
  top: 56px;
  animation-delay: -0.375s;
}
.ldio-ljewonjwdn9 > div:nth-child(5) {
  transform: rotate(180deg);
  transform-origin: 25.200000000000003px 62.2px;
}.ldio-ljewonjwdn9 div:nth-child(6) > div {
  left: 29px;
  top: 29px;
  animation-delay: -0.25s;
}
.ldio-ljewonjwdn9 > div:nth-child(6) {
  transform: rotate(225deg);
  transform-origin: 35.2px 35.2px;
}.ldio-ljewonjwdn9 div:nth-child(7) > div {
  left: 56px;
  top: 19px;
  animation-delay: -0.125s;
}
.ldio-ljewonjwdn9 > div:nth-child(7) {
  transform: rotate(270deg);
  transform-origin: 62.2px 25.200000000000003px;
}.ldio-ljewonjwdn9 div:nth-child(8) > div {
  left: 82px;
  top: 29px;
  animation-delay: 0s;
}
.ldio-ljewonjwdn9 > div:nth-child(8) {
  transform: rotate(315deg);
  transform-origin: 88.2px 35.2px;
}
.loadingio-spinner-spin-s5l4bjrd8ke {
  width: 124px;
  height: 124px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-ljewonjwdn9 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ljewonjwdn9 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
